from dataclasses import dataclass, field
from typing import Any

from app.cognition.knowledge.knowledge_operation_type import (
    KnowledgeOperationType,
)


@dataclass(frozen=True, slots=True)
class KnowledgeOperation:
    """
    Represents an atomic knowledge operation generated by
    the cognitive pipeline.
    """

    operation: KnowledgeOperationType

    target: str | None = None

    payload: dict[str, Any] = field(default_factory=dict)
